version: '3.8'
services:
  stats-server:
    build: /stats/stats-server
    image: stats-server
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - BD=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
  db:
    image: postgres:13.7-alpine
    container_name: some_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432
  main-service:
    build: /main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - db
    environment:
      - BD=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

